name: CI/CD

on: [push, pull_request]

jobs:
# https://docs.github.com/en/actions/guides/building-and-testing-python#testing-your-code
  run-tests:
    name: Run tests and linters (with tox)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: |
          pip install tox
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Test against listed Python versions
        # Run tox using the version of Python in `PATH`
        run: tox -e py
      - name: Run black
        run: tox -e black
      - name: Run pylama
        run: tox -e pylama

# https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
  build-publish:
    name: Publish Python distributions to TestPyPI
    runs-on: ubuntu-latest
    needs: run-tests  # only run when tests where successful
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: |
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel  --outdir dist/ .
      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

  build-publish-tags:
    name: Publish Python distributions to PyPI
    runs-on: ubuntu-latest
    needs: run-tests  # only run when tests where successful
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: |
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel  --outdir dist/ .
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
